#!/bin/sh



RMMOD="/usr/sbin/rmmod"

usage() {
		cat <<EOF
Usage: $0 [0|1|help]
EOF
		exit 1
}
wifi_force_up() {
	

	
	if [ -x /sbin/uci ]; then
		/usr/sbin/insmod cfg80211   	;sleep 0
		/usr/sbin/insmod mac80211   	;sleep 0
		/usr/sbin/insmod rt2x00lib  	;sleep 0
		/usr/sbin/insmod rt2x00mmio 	;sleep 0
		/usr/sbin/insmod rt2800lib  	;sleep 0
		/usr/sbin/insmod rt2800mmio 	;sleep 0
		/usr/sbin/insmod rt2x00pci  	;sleep 0
		/usr/sbin/insmod rt2800pci  	;sleep 0

		uci set wireless.radio0.disabled=0
		
		#sleep 0; wifi reload; wifi detect; sleep 0
		
		wifi
		
	fi		
		
}


wifi_force_down() {
	
	
	if [ -x /sbin/uci ]; then
		

		#. /usr/share/libubox/jshn.sh
		
		while wifi status | grep -E pending.*true > /dev/null; do sleep 1; done
		
		#json_load "$(wifi status)"
		#json_get_keys wifi_radio
		
		
	
		/sbin/uci set wireless.radio0.disabled=1
		
		/sbin/wifi down > /dev/null
		
		while wifi status | grep -E pending.*true > /dev/null; do sleep 1; done
		
		/usr/sbin/rmmod rt2800pci  	;sleep 0
		/usr/sbin/rmmod rt2x00pci  	;sleep 0
		/usr/sbin/rmmod rt2800mmio 	;sleep 0
		/usr/sbin/rmmod rt2800lib  	;sleep 0
		/usr/sbin/rmmod rt2x00mmio 	;sleep 0
		/usr/sbin/rmmod rt2x00lib  	;sleep 0
		/usr/sbin/rmmod mac80211   	;sleep 0
		/usr/sbin/rmmod cfg80211   	;sleep 0	
	fi
	
	/usr/bin/killall hostapd 2>/dev/null >/dev/null
	
	
}


case "$1" in
		1) wifi_force_up;;
		0) wifi_force_down;;
		*) usage;;
esac

